### ISSUE TITLE
Can't install slate-editor-icons

### ISSUE THREAD

**Issue by sajinshrestha** [Canner/slate-editor-icons#46]
```
$ npm i slate-editor-icons
npm ERR! code E404
npm ERR! 404 Not found : @canner/emoji-mart
npm ERR! 404
npm ERR! 404  '@canner/emoji-mart' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'slate-editor-icons'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by chilijung** [comment]
@sajinshrestha you shouldn't directly install `slate-editor-icons`, this repo only manages icons allowing editors to install shared editor components. You have to pick icons you want to install [list here](https://github.com/Canner/slate-editor-icons#packages).

If you don't want to assemble yourself, you could install packed package.
- https://github.com/Canner/canner-slate-editor
- https://github.com/Canner/slate-toolbar
- https://github.com/Canner/slate-md-editor

These are all based on `slate-editor-icons`'s packages

**Comment by sajinshrestha** [comment]
Thanks. I'll give it a try. 

FYI - I came across the `npm install --save slate-editor-icons` instruction from https://yarnpkg.com/en/package/slate-editor-icons which is linked from [slatejs](https://docs.slatejs.org/general/plugins) docs.
