### ISSUE TITLE
imageNode.js does not match the corresponding path on disk ImageNode.js, 

### ISSUE THREAD

**Issue by wmahad** [Canner/slate-editor-icons#63]
This error shows up in the slate-icon-image package. Below is an example of such an error.

`./node_modules/@canner/slate-icon-image/lib/index.js
Module not found: /Users/user1/projects/slate-editor/node_modules/@canner/slate-editor-renderer/lib/imageNode.js does not match the corresponding path on disk ImageNode.js.`

**Comment by Emsu** [comment]
Getting the same issue

**Comment by chilijung** [comment]
Thanks! This is fix in version 1.2.9!
