### ISSUE TITLE
Inserted table from table plugin has the wrong number or row and cloumn

### ISSUE THREAD

**Issue by ShawTim** [Canner/slate-editor-icons#66]
on [demo site](https://canner.github.io/slate-editor-icons/), try to insert a 3x3 table: 

![3x3](https://user-images.githubusercontent.com/85455/42160202-ece77002-7e28-11e8-92be-ae7526e2390b.png)

but what you actually get is a 2x2 table:

![screenshot-2018-7-2 slate-editor-icons](https://user-images.githubusercontent.com/85455/42160246-14ff6dba-7e29-11e8-9ec6-0dbfa42878ca.png)

**Comment by chilijung** [comment]
fixed thanks!
